// External dependency
const functions = require('firebase-functions');


// Required keys for serviceAccountKey.json
PROJECT_ID_SERVICE_ACCOUNT = "";
PRIVATE_KEY_ID_SERVICE_ACCOUNT= "";
PRIVATE_KEY_SERVICE_ACCOUNT= "";
CLIENT_EMAIL_SERVICE_ACCOUNT= "";
CLIENT_ID_SERVICE_ACCOUNT= "";
CLIENT_X509_CERT_URL_SERVICE_ACCOUNT= "";
// Required key for Open AI
const API_KEY_OPENAI_PROD = "";
// Required keys for WhatsApp Business
const ACCESS_TOKEN_WHATSAPP_BUSINESS = ""
const PHONE_NUMBER_ID_WHATSAPP_BUSINESS = ""
const ACCESS_TOKEN_WEBHOOK_WHATSAPP_BUSINESS = ""
// Required keys for Pinecone
const API_KEY_PINECONE_PROD = ""

module.exports = {
    PROJECT_ID_SERVICE_ACCOUNT,
    PRIVATE_KEY_ID_SERVICE_ACCOUNT,
    PRIVATE_KEY_SERVICE_ACCOUNT,
    CLIENT_EMAIL_SERVICE_ACCOUNT,
    CLIENT_ID_SERVICE_ACCOUNT,
    CLIENT_X509_CERT_URL_SERVICE_ACCOUNT,
    API_KEY_OPENAI_PROD,
    ACCESS_TOKEN_WHATSAPP_BUSINESS,
    PHONE_NUMBER_ID_WHATSAPP_BUSINESS,
    ACCESS_TOKEN_WEBHOOK_WHATSAPP_BUSINESS,
    API_KEY_PINECONE_PROD
};
